services:
  database:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    volumes:
      - ./public:/usr/src/app/public
      - ./database:/usr/src/app/database
    depends_on:
      - database
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
    name: arkham-horror-network
    driver: bridge