module.exports = {
  moduleNameMapper: {
    '^@Configs/(.*)$': '<rootDir>/configs/$1',
    '^@Controllers/(.*)$': '<rootDir>/controllers/$1',
    '^@Dtos/(.*)$': '<rootDir>/dtos/$1',
    '^@Entities/(.*)$': '<rootDir>/entities/$1',
    '^@Enums/(.*)$': '<rootDir>/enums/$1',
    '^@Exceptions/(.*)$': '<rootDir>/exceptions/$1',
    '^@Helpers/(.*)$': '<rootDir>/helpers/$1',
    '^@Modules/(.*)$': '<rootDir>/modules/$1',
    '^@Providers/(.*)$': '<rootDir>/providers/$1',
    '^@Repositories/(.*)$': '<rootDir>/repositories/$1',
    '^@Requests/(.*)$': '<rootDir>/requests/$1',
    '^@Services/(.*)$': '<rootDir>/services/$1',
    '^@Types/(.*)$': '<rootDir>/types/$1',
    '^@Interceptors/(.*)$': '<rootDir>/interceptors/$1',
    '^@Guards/(.*)$': '<rootDir>/guards/$1',
    '^@Decorators/(.*)$': '<rootDir>/decorators/$1',
    '^@Templates/(.*)$': '<rootDir>/templates/$1',
    '^@Middlewares/(.*)$': '<rootDir>/middlewares/$1',
    '^@Gateways/(.*)$': '<rootDir>/gateways/$1',
    '^@Responses/(.*)$': '<rootDir>/responses/$1',
  },
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: ['**/*.(t|j)s'],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
};
