export enum ErrorEnum {
  SOMETHING_WRONG = 'SOMETHING_WRONG',
  NOT_FOUND = 'NOT_FOUND',
  FILE_MISSING = 'FILE_MISSING',
  FILE_WRONG_FILE_TYPE = 'FILE_WRONG_FILE_TYPE',
  FILE_MAXIMUM_SIZE_EXCEEDED = 'FILE_MAXIMUM_SIZE_EXCEEDED',
  FILE_DELETE_FAILED = 'FILE_DELETE_FAILED',
}
